/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE RACER_LAP PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* 
*/
public class msg_racer_lap extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_RACER_LAP = 25;
    public static final int MAVLINK_MSG_LENGTH = 10;
    private static final long serialVersionUID = MAVLINK_MSG_ID_RACER_LAP;


      
    /**
    * Timestamp (miliseconds since UNIX epoch or miliseconds since boot time)
    */
    public long time_ms;
      
    /**
    * Lap time in miliseconds
    */
    public long lap_time_ms;
      
    /**
    * Lap number since heat start
    */
    public short lap_number;
      
    /**
    * Racer number. (Assigned id of racer)
    */
    public short racer_id;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_RACER_LAP;
              
        packet.payload.putUnsignedInt(time_ms);
              
        packet.payload.putUnsignedInt(lap_time_ms);
              
        packet.payload.putUnsignedByte(lap_number);
              
        packet.payload.putUnsignedByte(racer_id);
        
        return packet;
    }

    /**
    * Decode a racer_lap message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time_ms = payload.getUnsignedInt();
              
        this.lap_time_ms = payload.getUnsignedInt();
              
        this.lap_number = payload.getUnsignedByte();
              
        this.racer_id = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_racer_lap(){
        msgid = MAVLINK_MSG_ID_RACER_LAP;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_racer_lap(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_RACER_LAP;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_RACER_LAP - sysid:"+sysid+" compid:"+compid+" time_ms:"+time_ms+" lap_time_ms:"+lap_time_ms+" lap_number:"+lap_number+" racer_id:"+racer_id+"";
    }
}
        