/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SYS_STATUS PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* The general system state
*/
public class msg_sys_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SYS_STATUS = 1;
    public static final int MAVLINK_MSG_LENGTH = 6;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SYS_STATUS;


      
    /**
    * Battery voltage in mV
    */
    public int voltage_battery;
      
    /**
    * CPU load in percent (0%:0, 100%:1000)
    */
    public int load;
      
    /**
    * Communication drops in percent, (0%: 0, 100%: 10'000), (UART, I2C, SPI, CAN), dropped packets on all links (packets that were corrupted on reception)
    */
    public int drop_rate_comm;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SYS_STATUS;
              
        packet.payload.putUnsignedShort(voltage_battery);
              
        packet.payload.putUnsignedShort(load);
              
        packet.payload.putUnsignedShort(drop_rate_comm);
        
        return packet;
    }

    /**
    * Decode a sys_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.voltage_battery = payload.getUnsignedShort();
              
        this.load = payload.getUnsignedShort();
              
        this.drop_rate_comm = payload.getUnsignedShort();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_sys_status(){
        msgid = MAVLINK_MSG_ID_SYS_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_sys_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SYS_STATUS;
        unpack(mavLinkPacket.payload);        
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SYS_STATUS - sysid:"+sysid+" compid:"+compid+" voltage_battery:"+voltage_battery+" load:"+load+" drop_rate_comm:"+drop_rate_comm+"";
    }
}
        