/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE VRX_STATUS PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* 
*/
public class msg_vrx_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_VRX_STATUS = 26;
    public static final int MAVLINK_MSG_LENGTH = 7;
    private static final long serialVersionUID = MAVLINK_MSG_ID_VRX_STATUS;


      
    /**
    * Video rx module frequency. If unknown set to 0
    */
    public int vrx_freq;
      
    /**
    * Raw rssi reading
    */
    public int rssi_raw;
      
    /**
    * Filtered rssi value
    */
    public int rssi;
      
    /**
    * Video rx module id. Should be same as assigned racer id
    */
    public short vrx_id;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_VRX_STATUS;
              
        packet.payload.putUnsignedShort(vrx_freq);
              
        packet.payload.putUnsignedShort(rssi_raw);
              
        packet.payload.putUnsignedShort(rssi);
              
        packet.payload.putUnsignedByte(vrx_id);
        
        return packet;
    }

    /**
    * Decode a vrx_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.vrx_freq = payload.getUnsignedShort();
              
        this.rssi_raw = payload.getUnsignedShort();
              
        this.rssi = payload.getUnsignedShort();
              
        this.vrx_id = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_vrx_status(){
        msgid = MAVLINK_MSG_ID_VRX_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_vrx_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_VRX_STATUS;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_VRX_STATUS - sysid:"+sysid+" compid:"+compid+" vrx_freq:"+vrx_freq+" rssi_raw:"+rssi_raw+" rssi:"+rssi+" vrx_id:"+vrx_id+"";
    }
}
        