/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class VTS_STATE {
   public static final int VTS_STATE_UNINIT = 1; /* Uninitialized system, state is unknown. | */
   public static final int VTS_STATE_BOOT = 2; /* System is booting up. | */
   public static final int VTS_STATE_CALIBRATING = 3; /* System is calibrating. | */
   public static final int VTS_STATE_ACTIVE = 4; /* System is active | */
   public static final int VTS_STATE_STANDBY = 5; /* System is on standby | */
   public static final int VTS_STATE_ENUM_END = 6; /*  | */
}
            