/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Commands to be executed by system component.
*/
public class VTS_CMD {
   public static final int VTS_CMD_START_RACE_COUNTDOWN = 0; /* Start race count down |Seconds till start| Random hold off time| Unix start time (ms)| Empty| Empty| Empty| Empty|  */
   public static final int VTS_CMD_START_CALIBRATION = 1; /* Start race count down |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int VTS_CMD_SET_FREQUENCY = 2; /* Start race count down |Racer id| Frequency (MHz)| Empty| Empty| Empty| Empty| Empty|  */
   public static final int VTS_CMD_ENUM_END = 3; /*  | */
}
            