/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Micro air vehicle / autopilot classes. This identifies the individual model.
*/
public class VTS_SYSTEM_TYPE {
   public static final int VTS_GENERIC_TIMER = 0; /* Generic timer module containing vrx | */
   public static final int VTS_RACE_ORGANIZER = 1; /* System controlling timer modules. | */
   public static final int VTS_SYSTEM_TYPE_ENUM_END = 2; /*  | */
}
            